### ISSUE TITLE
Feedback 2dejaars - Schets

### ISSUE THREAD

**Issue by ArexanK** [Patrickkhr/fix-the-flow-wireflow-interactive#9]
Maak nog een schets van like-button interactie.

**Comment by Patrickkhr** [comment]
Ik heb de schets toegevoegd!

https://github.com/Patrickkhr/fix-the-flow-wireflow-interactive/wiki/2.-Ontwerpen-%F0%9F%8E%A8#wireflow-en-breakdownschets-likebutton
